linters:
  enable:
    - gocyclo
    - gofmt
    - govet
    - ineffassign
    - lll
    - misspell
    - revive
    - staticcheck

linters-settings:
  gocyclo:
    min-complexity: 16

issues:
  include:
    - EXC0012
    - EXC0013
    - EXC0014
    - EXC0015
