version: "2"

linters:
  enable:
    - gocyclo
    - lll
    - misspell
    - revive
  settings:
    gocyclo:
      min-complexity: 15
  exclusions:
    presets:
      - std-error-handling

formatters:
  enable:
    - gofmt
