version: 2

builds:
  - env:
      - CGO_ENABLED=0
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s
      - -w
      - -X github.com/patrickhoefler/dockerfilegraph/internal/cmd.gitVersion={{.Version}}
      - -X github.com/patrickhoefler/dockerfilegraph/internal/cmd.gitCommit={{.Commit}}
      - -X github.com/patrickhoefler/dockerfilegraph/internal/cmd.buildDate={{.Date}}

changelog:
  disable: true

dockers_v2:
  - images:
      - 'ghcr.io/patrickhoefler/dockerfilegraph'
    tags:
      - 'latest'
      - '{{ .Major }}'
      - '{{ .Major }}.{{ .Minor }}'
      - '{{ .Major }}.{{ .Minor }}.{{ .Patch }}'
      # for backwards compatibility
      - 'alpine'
      - 'latest-alpine'
      - '{{ .Major }}-alpine'
      - '{{ .Major }}.{{ .Minor }}-alpine'
      - '{{ .Major }}.{{ .Minor }}.{{ .Patch }}-alpine'
    platforms:
      - linux/amd64
      - linux/arm64

homebrew_casks:
  - repository:
      owner: patrickhoefler
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    homepage: https://github.com/patrickhoefler/dockerfilegraph
    description: 'Visualize your multi-stage Dockerfile'
    dependencies:
      - formula: graphviz
