builds:
  - env:
      - CGO_ENABLED=0
    goarch:
      - amd64
    ldflags:
      - -s
      - -w
      - -X github.com/patrickhoefler/dockerfilegraph/internal/cmd.gitVersion={{.Version}}
      - -X github.com/patrickhoefler/dockerfilegraph/internal/cmd.gitCommit={{.Commit}}
      - -X github.com/patrickhoefler/dockerfilegraph/internal/cmd.buildDate={{.Date}}

changelog:
  skip: true

dockers:
  - dockerfile: Dockerfile
    image_templates:
      - 'ghcr.io/patrickhoefler/dockerfilegraph:latest'
      - 'ghcr.io/patrickhoefler/dockerfilegraph:{{ .Major }}'
      - 'ghcr.io/patrickhoefler/dockerfilegraph:{{ .Major }}.{{ .Minor }}'
      - 'ghcr.io/patrickhoefler/dockerfilegraph:{{ .Major }}.{{ .Minor }}.{{ .Patch }}'

  - dockerfile: Dockerfile.alpine
    image_templates:
      - 'ghcr.io/patrickhoefler/dockerfilegraph:alpine'
      - 'ghcr.io/patrickhoefler/dockerfilegraph:latest-alpine'
      - 'ghcr.io/patrickhoefler/dockerfilegraph:{{ .Major }}-alpine'
      - 'ghcr.io/patrickhoefler/dockerfilegraph:{{ .Major }}.{{ .Minor }}-alpine'
      - 'ghcr.io/patrickhoefler/dockerfilegraph:{{ .Major }}.{{ .Minor }}.{{ .Patch }}-alpine'

brews:
  - tap:
      owner: patrickhoefler
      name: homebrew-tap

    homepage: https://github.com/patrickhoefler/dockerfilegraph
    description: 'Visualize your multi-stage Dockerfile'

    dependencies:
      - graphviz
