name: "Container Scan"

on:
  schedule:
    - cron: "0 0 * * 1"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  grype:
    name: Grype
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@fa2e9d605c4eeb9fcad4c99c224cee0c6c7f3594 # v2.16.0
        with:
          egress-policy: audit

      - name: Run Grype vulnerability scanner on latest image
        uses: anchore/scan-action@e1165082ffb1fe366ebaf02d8526e7c4989ea9d2 # v7.4.0
        id: grype
        with:
          image: ghcr.io/patrickhoefler/dockerfilegraph:latest
          output-format: sarif
          fail-build: false
          grype-version: v0.110.0

      - name: Upload Grype results to GitHub Security
        uses: github/codeql-action/upload-sarif@38697555549f1db7851b81482ff19f1fa5c4fedc # v4.34.1
        with:
          sarif_file: ${{ steps.grype.outputs.sarif }}
          category: grype
